import { CostItem, RevenueItem } from './types';

// Sample cost data
export const costsData: CostItem[] = [
  {
    id: "c1",
    category: "Artist Fees",
    subcategory: "DJ",
    description: "Main headliner fee",
    event: "tf-2025",
    planned: 5000,
    actual: 5500,
    variance: -500,
    variancePercentage: -10,
    notes: "Rate increased due to recent chart success"
  },
  {
    id: "c2",
    category: "Venue Rental",
    subcategory: "Main Hall",
    description: "Rental fee for the main hall",
    event: "tf-2025",
    planned: 3000,
    actual: 3000,
    variance: 0,
    variancePercentage: 0
  },
  {
    id: "c3",
    category: "Marketing",
    subcategory: "Social Media Ads",
    description: "Advertising campaign on Facebook and Instagram",
    event: "tf-2025",
    planned: 1500,
    actual: 1200,
    variance: 300,
    variancePercentage: 20,
    notes: "Campaign was more efficient than expected"
  },
  {
    id: "c4",
    category: "Security",
    subcategory: "Guards",
    description: "Security personnel for the event",
    event: "tf-2025",
    planned: 2000,
    actual: 2200,
    variance: -200,
    variancePercentage: -10
  },
  {
    id: "c5",
    category: "Logistics",
    subcategory: "Transportation",
    description: "Transportation costs for equipment and staff",
    event: "tf-2025",
    planned: 800,
    actual: 750,
    variance: 50,
    variancePercentage: 6.25
  },
  {
    id: "c6",
    category: "Artist Fees",
    subcategory: "DJ",
    description: "Main headliner fee",
    event: "bn-2025",
    planned: 5000,
    actual: 5500,
    variance: -500,
    variancePercentage: -10,
    notes: "Rate increased due to recent chart success"
  },
  {
    id: "c7",
    category: "Venue Rental",
    subcategory: "Main Hall",
    description: "Rental fee for the main hall",
    event: "bn-2025",
    planned: 3000,
    actual: 3000,
    variance: 0,
    variancePercentage: 0
  },
  {
    id: "c8",
    category: "Marketing",
    subcategory: "Social Media Ads",
    description: "Advertising campaign on Facebook and Instagram",
    event: "bn-2025",
    planned: 1500,
    actual: 1200,
    variance: 300,
    variancePercentage: 20,
    notes: "Campaign was more efficient than expected"
  },
  {
    id: "c9",
    category: "Security",
    subcategory: "Guards",
    description: "Security personnel for the event",
    event: "bn-2025",
    planned: 2000,
    actual: 2200,
    variance: -200,
    variancePercentage: -10
  },
  {
    id: "c10",
    category: "Logistics",
    subcategory: "Transportation",
    description: "Transportation costs for equipment and staff",
    event: "bn-2025",
    planned: 800,
    actual: 750,
    variance: 50,
    variancePercentage: 6.25
  },
  {
    id: "c11",
    category: "Artist Fees",
    subcategory: "DJ",
    description: "Main headliner fee",
    event: "es-2025",
    planned: 5000,
    actual: 5500,
    variance: -500,
    variancePercentage: -10,
    notes: "Rate increased due to recent chart success"
  },
  {
    id: "c12",
    category: "Venue Rental",
    subcategory: "Main Hall",
    description: "Rental fee for the main hall",
    event: "es-2025",
    planned: 3000,
    actual: 3000,
    variance: 0,
    variancePercentage: 0
  },
  {
    id: "c13",
    category: "Marketing",
    subcategory: "Social Media Ads",
    description: "Advertising campaign on Facebook and Instagram",
    event: "es-2025",
    planned: 1500,
    actual: 1200,
    variance: 300,
    variancePercentage: 20,
    notes: "Campaign was more efficient than expected"
  },
  {
    id: "c14",
    category: "Security",
    subcategory: "Guards",
    description: "Security personnel for the event",
    event: "es-2025",
    planned: 2000,
    actual: 2200,
    variance: -200,
    variancePercentage: -10
  },
  {
    id: "c15",
    category: "Logistics",
    subcategory: "Transportation",
    description: "Transportation costs for equipment and staff",
    event: "es-2025",
    planned: 800,
    actual: 750,
    variance: 50,
    variancePercentage: 6.25
  },
  {
    id: "c16",
    category: "Artist Fees",
    subcategory: "DJ",
    description: "Main headliner fee",
    event: "boiler-room",
    planned: 5000,
    actual: 5500,
    variance: -500,
    variancePercentage: -10,
    notes: "Rate increased due to recent chart success"
  },
  {
    id: "c17",
    category: "Venue Rental",
    subcategory: "Main Hall",
    description: "Rental fee for the main hall",
    event: "boiler-room",
    planned: 3000,
    actual: 3000,
    variance: 0,
    variancePercentage: 0
  },
  {
    id: "c18",
    category: "Marketing",
    subcategory: "Social Media Ads",
    description: "Advertising campaign on Facebook and Instagram",
    event: "boiler-room",
    planned: 1500,
    actual: 1200,
    variance: 300,
    variancePercentage: 20,
    notes: "Campaign was more efficient than expected"
  },
  {
    id: "c19",
    category: "Security",
    subcategory: "Guards",
    description: "Security personnel for the event",
    event: "boiler-room",
    planned: 2000,
    actual: 2200,
    variance: -200,
    variancePercentage: -10
  },
  {
    id: "c20",
    category: "Logistics",
    subcategory: "Transportation",
    description: "Transportation costs for equipment and staff",
    event: "boiler-room",
    planned: 800,
    actual: 750,
    variance: 50,
    variancePercentage: 6.25
  },
];

// Sample revenue data
export const revenueData: RevenueItem[] = [
  {
    id: "r1",
    category: "Ticket Sales",
    subcategory: "Early Bird",
    description: "First batch tickets",
    event: "tf-2025",
    planned: 10000,
    actual: 12500,
    variance: 2500,
    variancePercentage: 25,
    vatPercent: 23
  },
  {
    id: "r2",
    category: "Sponsorship",
    subcategory: "Main Sponsor",
    description: "Sponsorship fee from main sponsor",
    event: "tf-2025",
    planned: 5000,
    actual: 5000,
    variance: 0,
    variancePercentage: 0,
    vatPercent: 0
  },
  {
    id: "r3",
    category: "Merchandise",
    subcategory: "T-Shirts",
    description: "Sales from T-shirts",
    event: "tf-2025",
    planned: 2000,
    actual: 2200,
    variance: 200,
    variancePercentage: 10,
    vatPercent: 23
  },
  {
    id: "r4",
    category: "Bar Sales",
    subcategory: "Alcohol",
    description: "Sales from alcohol",
    event: "tf-2025",
    planned: 4000,
    actual: 4500,
    variance: 500,
    variancePercentage: 12.5,
    vatPercent: 23
  },
  {
    id: "r5",
    category: "Food Sales",
    subcategory: "Snacks",
    description: "Sales from snacks",
    event: "tf-2025",
    planned: 1500,
    actual: 1600,
    variance: 100,
    variancePercentage: 6.67,
    vatPercent: 5
  },
  {
    id: "r6",
    category: "Ticket Sales",
    subcategory: "Early Bird",
    description: "First batch tickets",
    event: "bn-2025",
    planned: 10000,
    actual: 12500,
    variance: 2500,
    variancePercentage: 25,
    vatPercent: 23
  },
  {
    id: "r7",
    category: "Sponsorship",
    subcategory: "Main Sponsor",
    description: "Sponsorship fee from main sponsor",
    event: "bn-2025",
    planned: 5000,
    actual: 5000,
    variance: 0,
    variancePercentage: 0,
    vatPercent: 0
  },
  {
    id: "r8",
    category: "Merchandise",
    subcategory: "T-Shirts",
    description: "Sales from T-shirts",
    event: "bn-2025",
    planned: 2000,
    actual: 2200,
    variance: 200,
    variancePercentage: 10,
    vatPercent: 23
  },
  {
    id: "r9",
    category: "Bar Sales",
    subcategory: "Alcohol",
    description: "Sales from alcohol",
    event: "bn-2025",
    planned: 4000,
    actual: 4500,
    variance: 500,
    variancePercentage: 12.5,
    vatPercent: 23
  },
  {
    id: "r10",
    category: "Food Sales",
    subcategory: "Snacks",
    description: "Sales from snacks",
    event: "bn-2025",
    planned: 1500,
    actual: 1600,
    variance: 100,
    variancePercentage: 6.67,
    vatPercent: 5
  },
  {
    id: "r11",
    category: "Ticket Sales",
    subcategory: "Early Bird",
    description: "First batch tickets",
    event: "es-2025",
    planned: 10000,
    actual: 12500,
    variance: 2500,
    variancePercentage: 25,
    vatPercent: 23
  },
  {
    id: "r12",
    category: "Sponsorship",
    subcategory: "Main Sponsor",
    description: "Sponsorship fee from main sponsor",
    event: "es-2025",
    planned: 5000,
    actual: 5000,
    variance: 0,
    variancePercentage: 0,
    vatPercent: 0
  },
  {
    id: "r13",
    category: "Merchandise",
    subcategory: "T-Shirts",
    description: "Sales from T-shirts",
    event: "es-2025",
    planned: 2000,
    actual: 2200,
    variance: 200,
    variancePercentage: 10,
    vatPercent: 23
  },
  {
    id: "r14",
    category: "Bar Sales",
    subcategory: "Alcohol",
    description: "Sales from alcohol",
    event: "es-2025",
    planned: 4000,
    actual: 4500,
    variance: 500,
    variancePercentage: 12.5,
    vatPercent: 23
  },
  {
    id: "r15",
    category: "Food Sales",
    subcategory: "Snacks",
    description: "Sales from snacks",
    event: "es-2025",
    planned: 1500,
    actual: 1600,
    variance: 100,
    variancePercentage: 6.67,
    vatPercent: 5
  },
  {
    id: "r16",
    category: "Ticket Sales",
    subcategory: "Early Bird",
    description: "First batch tickets",
    event: "boiler-room",
    planned: 10000,
    actual: 12500,
    variance: 2500,
    variancePercentage: 25,
    vatPercent: 23
  },
  {
    id: "r17",
    category: "Sponsorship",
    subcategory: "Main Sponsor",
    description: "Sponsorship fee from main sponsor",
    event: "boiler-room",
    planned: 5000,
    actual: 5000,
    variance: 0,
    variancePercentage: 0,
    vatPercent: 0
  },
  {
    id: "r18",
    category: "Merchandise",
    subcategory: "T-Shirts",
    description: "Sales from T-shirts",
    event: "boiler-room",
    planned: 2000,
    actual: 2200,
    variance: 200,
    variancePercentage: 10,
    vatPercent: 23
  },
  {
    id: "r19",
    category: "Bar Sales",
    subcategory: "Alcohol",
    description: "Sales from alcohol",
    event: "boiler-room",
    planned: 4000,
    actual: 4500,
    variance: 500,
    variancePercentage: 12.5,
    vatPercent: 23
  },
  {
    id: "r20",
    category: "Food Sales",
    subcategory: "Snacks",
    description: "Sales from snacks",
    event: "boiler-room",
    planned: 1500,
    actual: 1600,
    variance: 100,
    variancePercentage: 6.67,
    vatPercent: 5
  },
];
